version: "3.8"

services:
  backend:
    build: .
    container_name: zenlms-backend
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    container_name: zenlms-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
