package com.MiniLms.LMSBackend.dto.ResponseDTO.ContentResponseDTO;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;


@Data
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class CommonContentResponseDTO {
    private String id; // usually autogenerated by MongoDB or set manually
    private String name;
}
